

/**
 * Application route constants
 */

// Route paths
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  STUDENT: "/student",
  TEACHER: "/teacher",
  CLASS: "/class",
  ATTENDANCE: "/attendance",
  ATTENDANCE_CHILD: "/attendance/child",
  ATTENDANCE_ME: "/attendance/me",
  COMPLAINT: "/complaint",
  PARENT_COMPLAINT: "/parent-complaint",
  PARENT_PORTAL: "/parent-portal",
  PARENT_DASHBOARD: "/parent-portal/dashboard",
  PARENT_ACADEMIC: "/parent-portal/academic",
  PARENT_ATTENDANCE: "/parent-portal/attendance",
  PARENT_DISCIPLINE: "/parent-portal/discipline",
  PARENT_ASSIGNMENTS: "/parent-portal/assignments",
  PARENT_NOTIFICATIONS: "/parent-portal/notifications",
  PARENT_CHILD_PROGRESS: "/parent-portal/child-progress",
  COUNSELING: "/counseling",
  COUNSELING_MANAGE: "/counseling/manage",
  COUNSELING_SESSION: "/counseling/session",
  COUNSELING_REQUEST: "/counseling/request",
  PERMISSION: "/permission",
  PERMISSION_CREATE: "/permission/create",
  STUDENT_DATA: "/student-data",
  STUDENT_PROFILE: "/student-data/profile",
  STUDENT_MY_PROFILE: "/student/profile",
  STUDENT_SCHEDULE: "/student/schedule",
  STUDENT_ACTIVITIES: "/student-activities",
  CLASS_JOURNAL: "/class-journal", 
  CLASS_JOURNAL_CREATE: "/class-journal/create",
  TEACHER_SCHEDULE: "/teacher/schedule",
  TEACHER_CLASS_MANAGEMENT: "/teacher/class-management",
  DISCIPLINE: "/discipline",
  DISCIPLINE_RECORD: "/discipline/record",
  DISCIPLINE_MANAGE: "/discipline/manage",
  ACHIEVEMENTS: "/achievements",
  CERTIFICATES: "/certificates",
  EXTRACURRICULAR: "/extracurricular",
  EXTRACURRICULAR_MANAGE: "/extracurricular/manage",
  EXTRACURRICULAR_ATTENDANCE: "/extracurricular/attendance",
  EXTRACURRICULAR_JOURNAL: "/extracurricular/journal",
  EXTRACURRICULAR_TRAINING: "/extracurricular/training",
  CALENDAR: "/calendar",
  CALENDAR_CREATE: "/calendar/create",
  ANNOUNCEMENT: "/announcement",
  ANNOUNCEMENT_MANAGE: "/announcement/manage",
  ANNOUNCEMENT_VIEW: "/announcement/view",
  PROPOSAL: "/proposal",
  REPORTS: "/reports",
  SETTINGS: "/settings",
  GAMIFICATION: "/gamification",
  NOTIFICATIONS: "/notifications",
  NOT_FOUND: "*"
};

